### PR TITLE
Feature | Add support for Laravel 11

### PR DESCRIPTION
**Pull request by Sammyjo20**
This PR introduces support for Laravel 11 and drops support for Laravel 10.

### CODE REVIEW

**Review by Sammyjo20 — COMMENTED** [review]
Self review

**Review by pristavu — APPROVED** [review]

**Review by pristavu — APPROVED** [review]

**Review by krzysztofrewak — APPROVED** [review]

**Comment by krzysztofrewak** [comment]
@Sammyjo20, could you look at this again?

**Comment by Ninako** [comment]
@Sammyjo20 would you please take a look? Thank you)

**Comment by Sammyjo20** [comment]
Done @Ninako @krzysztofrewak

**Pull request merged**
