### PR TITLE
Add support for parallel testing

### PR DESCRIPTION
**Pull request by hendrikheil**
This PR is based on the idea proposed in https://github.com/PlannrCrm/laravel-fast-refresh-database/issues/15

### CODE REVIEW

**Comment by hendrikheil** [comment]
@Sammyjo20 is this still considered for merging? If not, I'll close the PR :)

**Comment by Sammyjo20** [comment]
Hey @hendrikheil Absolutely! Apologies I have been busy - I will take a look this evening :)

**Comment by Sammyjo20** [comment]
Sorry for the delay @hendrikheil - I will have the team look into this :)

**Review by Sammyjo20 — APPROVED** [review]
Code looks great! Just going to test this locally

**Comment by Sammyjo20** [comment]
Works well @hendrikheil thank you for this - so sorry for the delay!

**Pull request merged**
